#!/bin/bash

# Compile everything without making object files first, 
# because that breaks gsl for som eunknown reason.

OS=$(uname -s)
echo "platform: $OS"

mkdir build
gcc -Os src/*.c platform/$OS/*.c -o build/subchemica\
 -Wall -Wextra -lgsl -Iinclude -I/usr/local/include -L/usr/local/lib\
 -fstack-usage
